-- Usuwanie tabel, jeśli istnieją
DROP TABLE IF EXISTS medical_treatment CASCADE;
DROP TABLE IF EXISTS visit CASCADE;
DROP TABLE IF EXISTS patient CASCADE;
DROP TABLE IF EXISTS doctor CASCADE;
DROP TABLE IF EXISTS address CASCADE;

-- Tworzenie tabel
CREATE TABLE IF NOT EXISTS doctor (
                                      id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                      first_name VARCHAR(255) NOT NULL,
                                      last_name VARCHAR(255) NOT NULL,
                                      specialization VARCHAR(255),
                                      CONSTRAINT pk_doctor PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS patient (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                       first_name VARCHAR(255) NOT NULL,
                                       last_name VARCHAR(255) NOT NULL,
                                       date_of_birth DATE NOT NULL,
                                       version BIGINT NOT NULL,
                                       CONSTRAINT pk_patient PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS address (
                                       id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                       address_line1 VARCHAR(255),
                                       address_line2 VARCHAR(255),
                                       city VARCHAR(255),
                                       postal_code VARCHAR(255),
                                       CONSTRAINT pk_address PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS visit (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                     description VARCHAR(255),
                                     visit_date_time TIMESTAMP NOT NULL,
                                     doctor_id BIGINT,
                                     patient_id BIGINT,
                                     CONSTRAINT pk_visit PRIMARY KEY (id),
                                     CONSTRAINT fk_visit_on_doctor FOREIGN KEY (doctor_id) REFERENCES doctor (id),
                                     CONSTRAINT fk_visit_on_patient FOREIGN KEY (patient_id) REFERENCES patient (id)
);

CREATE TABLE IF NOT EXISTS medical_treatment (
                                                 id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                                                 type VARCHAR(255),
                                                 visit_id BIGINT,
                                                 CONSTRAINT pk_medical_treatment PRIMARY KEY (id),
                                                 CONSTRAINT fk_medical_treatment_on_visit FOREIGN KEY (visit_id) REFERENCES visit (id)
);

-- Insert dla DoctorEntity
INSERT INTO doctor (first_name, last_name, specialization) VALUES
                                                               ('Alice', 'Brown', 'Kardiolog'),
                                                               ('David', 'Clark', 'Neurolog'),
                                                               ('Sophia', 'Lopez', 'Pediatra'),
                                                               ('Michael', 'Smith', 'Ortopeda');

-- Insert dla PatientEntity (różne nazwiska, daty urodzenia, wersja)
INSERT INTO patient (first_name, last_name, date_of_birth, version) VALUES
                                                                        ('Liam', 'Kowalski', '1995-06-15', 0),
                                                                        ('Emma', 'Kowalski', '1992-12-25', 0),
                                                                        ('Noah', 'Nowak', '1980-02-10', 0),
                                                                        ('Olivia', 'Wiśniewska', '2000-08-20', 0),
                                                                        ('Ava', 'Zielińska', '1975-03-05', 0);

-- Insert dla AddressEntity
INSERT INTO address (address_line1, address_line2, city, postal_code) VALUES
                                                                          ('Main Street', 'Apt 1', 'Warsaw', '00-001'),
                                                                          ('Park Avenue', 'Suite 2', 'Krakow', '30-002'),
                                                                          ('Sunny Road', NULL, 'Gdansk', '80-003'),
                                                                          ('Oak Lane', 'Flat 5', 'Wroclaw', '50-004'),
                                                                          ('River Road', NULL, 'Poznan', '60-005');

-- Insert dla VisitEntity (różna liczba wizyt dla pacjentów)
INSERT INTO visit (description, visit_date_time, doctor_id, patient_id) VALUES
                                                                            ('Routine Check', '2024-05-01 11:00:00', 1, 1), -- Liam Kowalski
                                                                            ('Follow-up', '2024-06-01 12:00:00', 2, 1),      -- Liam Kowalski
                                                                            ('Annual Exam', '2024-04-10 10:30:00', 2, 2),    -- Emma Kowalski
                                                                            ('Specialist Consult', '2024-04-15 13:00:00', 3, 3), -- Noah Nowak
                                                                            ('Therapy Session', '2024-04-05 14:45:00', 1, 3),    -- Noah Nowak
                                                                            ('Check-up', '2024-07-01 09:00:00', 4, 3),          -- Noah Nowak
                                                                            ('Consultation', '2024-03-20 15:00:00', 3, 4),      -- Olivia Wiśniewska
                                                                            ('Emergency Visit', '2024-08-10 16:00:00', 2, 5);   -- Ava Zielińska

-- Insert dla MedicalTreatmentEntity
INSERT INTO medical_treatment (type, visit_id) VALUES
                                                   ('DIAGNOSIS', 1),
                                                   ('MEDICATION', 2),
                                                   ('THERAPY', 3),
                                                   ('SURGERY', 4),
                                                   ('DIAGNOSIS', 5),
                                                   ('MEDICATION', 6),
                                                   ('THERAPY', 7),
                                                   ('SURGERY', 8);